### ISSUE TITLE
Implementing a callback for unreachable URLs/paths

### ISSUE THREAD

**Issue by Sheddy94** [SrejonKhan/AsyncImageLibrary#6]
Hello @SrejonKhan ,
How to implement a callback when a URL/path is unreachable? Return true for successful PathResolved and false when failed to resolve the path.

Example:

``AsyncImage image = new AsyncImage(path);
image.OnPathResolved += (result) =>
{
   // result is boolean
   Debug.Log("PathFound =" + result);
};

I am mostly interested in loading an image from a remote location to automatically rerun the load image function when the internet connection is lost and then resorted. Currently, I have to manually run the function again. Thanks.

**Comment by SrejonKhan** [comment]
@Sheddy94 Hello, this would be a great addition to the library and I'd be happy to work on it. 

Here's how I envision implementing this:
1. We can define an Action<bool> delegate in[ AsyncImage.cs](https://github.com/SrejonKhan/AsyncImageLibrary/blob/39dba70db6efe1d8be14b65a4f1602c5114c7bbc/Runtime/Core/AsyncImage.cs#L38) named OnPathValidated or something similar. This delegate will be invoked with a boolean parameter indicating whether the path is reachable.
2. When loading an image from a [local file from a file stream,](https://github.com/SrejonKhan/AsyncImageLibrary/blob/39dba70db6efe1d8be14b65a4f1602c5114c7bbc/Runtime/Core/ImageLoadSave.cs#L49) we can leverage File.Exists(string path) from System.IO to verify the file's existence before invoking OnPathValidated with the appropriate value (true for success).
3. In the case of [loading an image from a remote location](https://github.com/SrejonKhan/AsyncImageLibrary/blob/39dba70db6efe1d8be14b65a4f1602c5114c7bbc/Runtime/Core/ImageLoadSave.cs#L66) using the UnityWebRequest (UWR), we can leverage UnityWebRequest.Head(string url) to send a HEAD request and check the response code. The path is reachable if the code is greater than or equal to 200 (indicating a success). In this case, you can just trigger OnPathValidated with true; otherwise, trigger it with false.

I believe this feature will be valuable for users who need to handle image loading failures gracefully and automatically retry loading when the internet connection is restored.

I'll keep you updated on the progress of this feature. Please let me know if you have any further questions or suggestions.

**Comment by SrejonKhan** [comment]
Hello @Sheddy94, I've just pushed some commits on the main branch that introduces `ValidatePath()` method, `OnPathValidation` delegate, and `IsPathValidated` property. I hope that enhances the enhancement we are looking for. Let me know if something is missed unintentionally. I'm closing the issue for now. Feel free to open it again if you need to.
